# wrappers around R6Flow following standard R functionality


# !diagnostics suppress=., 


make_fn_key <- function(fn, rflow_options, eddy) {
    
    # unique fn_key = hash of fn's defined arguments and body
    fn_formals <- formals(args(fn))
    arg_chr <- paste(
        paste(names(fn_formals), as.character(fn_formals), sep = "="),
        collapse = ", "
    )
    body_chr <- as.character(body(fn))
    rfo_chr <- 
        rflow_options %>%
        discard_at("eddy") %>%
        format()
    fn_key <- eddy$digest(c(arg_chr, body_chr, rfo_chr))
    
    fn_key
}


#' Explicit cache of a function.
#' 
#' @param fn Function to be cached, ideally a pure function.
#' @param rflow_options List of options created using \code{get_rflow_options}.
#' 
#' @return The cached version of the function.
#' 
#' @export
make_rf <- function(fn,
                    rflow_options = get_rflow_options()) {
    
    stopifnot(is.function(fn))
    if (any(grepl("\\.Primitive", format(fn)))) {
        rlang::abort("Primitive functions not supported.")
    }
    
    # when generated by get_rflow_options(), rflow_options are valid
    rfo <- rflow_options
    if (!is.null(rfo$eval_arg_fn)) {
        fn_formals <- formals(args(fn))
        eval_arg_fn_formals <- formals(args(rfo$eval_arg_fn))
        stopifnot(identical(fn_formals, eval_arg_fn_formals))
    }
    eddy <- rflow_options$eddy
    
    # best place to capture the name of the function
    # fn_name (the binding) is irrelevant (it's the args and body that matter)
    # but it may be useful for debugging
    match_call <- match.call()
    if (is.symbol(match_call$fn)) {
        fn_name <- as.character(match_call$fn)
    } else {
        rlang::abort("Anonymous functions not supported.")
    }
    fn_key <- make_fn_key(fn, rflow_options, eddy)
    
    if (eddy$has_rflow(fn_key)) {
        # the R6Flow obj exists in eddy, we can use it
        rflow <- eddy$get_rflow(fn_key)
    } else {
        # the R6Flow obj does exists in eddy, but fn_key may have data in cache
        rflow <- R6Flow$new(
            fn = fn,
            fn_key = fn_key,
            fn_name = fn_name,
            rflow_options = rflow_options
        )
    }
    
    rflow$rf_fn
}


#' Implicit cache of a function and processing of the given call.
#' 
#' @param fn_call Function call to be processed.
#' @param rflow_options List of options created using \code{get_rflow_options}.
#' 
#' @return The cached version of the function.
#' 
#' @export
rf <- function(fn_call, 
               rflow_options = get_rflow_options()) {
    
    # fn_call will be replaced by its original call
    # this is to avoid triggering evaluation of fn_call
    fn_call <- parse_call()
    fn <- eval(fn_call[[1L]])
    stopifnot(is.function(fn))
    
    # when generated by get_rflow_options(), rflow_options are valid
    rfo <- rflow_options
    if (!is.null(rfo$eval_arg_fn)) {
        fn_formals <- formals(args(fn))
        eval_arg_fn_formals <- formals(args(rfo$eval_arg_fn))
        stopifnot(identical(fn_formals, eval_arg_fn_formals))
    }
    eddy <- rflow_options$eddy
    
    if (is.symbol(fn_call[[1L]])) {
        fn_name <- as.character(fn_call[[1L]])
    } else {
        rlang::abort("Anonymous functions not supported.")
    }
    fn_key <- make_fn_key(fn, rflow_options, eddy)
    
    if (eddy$has_rflow(fn_key)) {
        rflow <- eddy$get_rflow(fn_key)
    } else {
        rflow <- R6Flow$new(
            fn = fn,
            fn_key = fn_key,
            fn_name = fn_name,
            rflow_options = rflow_options
        )
    }
    
    # unlike make_rf, we have a fn call to process (in the parent.env!)
    fn_call[[1L]] <- rflow$rf_fn
    res <- eval(fn_call, envir = parent.frame())
    
    res
}


#' @importFrom dplyr collect
#' @name collect
#' @rdname collect.R6Flow
#' @export
NULL


#' Get the data from an \code{R6Flow} or an \code{Element} object.
#' 
#' @param x An rflow object, e.g. as returned by \code{\link{rf}}.
#' @param ... Element of the output data to be selected. If present, it must
#'   be named \code{name}. otherwise the first item of the \code{...} list
#'   will be used. The default is \code{name = NULL}, which returns all the
#'   data.
#' 
#' @return Data associated with the output of the function.
#' 
#' @method collect R6Flow
#' @export
collect.R6Flow <- function(x, ...) {
    
    arg_lst <- list(...)
    arg_name <- if ("name" %in% names(arg_lst) || length(arg_lst) == 0L) {
        # NULL if no arguments present
        arg_lst$name
    } else {
        # there is at least one argument, not `name`; assume it is `name`
        arg_lst[[1L]]
    }
    x$collect(name = arg_name)
}


#' @rdname collect.R6Flow
#' 
#' @method collect Element
#' @export
collect.Element <- function(x, ...) {
    
    if (length(list(...)) > 0L) warning("all other arguments ignored")
    
    x$self$collect(name = x$elem_name)
}


#' Extract an element from an \code{R6Flow} object.
#' 
#' @param rflow An rflow object, e.g. as returned by \code{\link{rf}}.
#' @param name Element of the output data to be selected. The default is 
#'   \code{name = NULL}, which returns the element version of the \code{R6Flow} 
#'   input object.
#' 
#' @return An object with class \code{Element}.
#' 
#' @export
element <- function(rflow, name = NULL) {
    
    stopifnot(inherits(rflow, "R6Flow"))
    
    rflow$get_element(name = name)
}


#' @rdname element
#' 
#' @export
`[.R6Flow` <- function(rflow, name) {
    
    if (missing(name)) {
        rflow$get_element()
    } else {
        rflow$get_element(name = name)
    }
}


#' Is the rflow in a valid state?
#' 
#' It is used mostly for diagnostic purposes. Invalid states also occur
#'   when the object is reconstructed from cache before any function call,
#'   i.e., as in the case of \code{\link{make_rf}}.
#' 
#' @param rflow An rflow object, e.g. as returned by \code{\link{rf}}.
#' 
#' @return A logical value, whether the current state is valid.
#' 
#' @export
is_valid <- function(rflow) {
    
    stopifnot(inherits(rflow, "R6Flow"))
    
    rflow$is_valid
}


#' Is the current state computed (stored in the cache)?
#' 
#' @param rflow An rflow object, e.g. as returned by \code{\link{rf}}.
#' 
#' @return A logical value, whether the value can be obtained without
#'   triggering the computation chain.
#' 
#' @export
is_computed <- function(rflow) {
    
    stopifnot(inherits(rflow, "R6Flow"))
    
    rflow$is_computed
}


#' Forgets the computation for the current state.
#' 
#' @param rflow An rflow object, e.g. as returned by \code{\link{rf}}.
#' 
#' @return A logical value, whether the deletion was successful.
#' 
#' @export
forget <- function(rflow) {
    
    stopifnot(inherits(rflow, "R6Flow"))
    
    if (!rflow$is_valid) {
        rlang::abort("rflow not valid, cannot determine state to delete.")
    }
    
    rflow$delete_state(rflow$state_index)
}
